List<Map<String, dynamic>> dataInf = [
  {
    'imageUrl': 'images/bage1.jpg',
    'title': 'Fire Cat',
    'description': 'Fire Cat ~~ Fire Cat ~~ 10 pieces available',
    'id': 0,
    'price': 23.3,
    'code': '252',
  },
  {
    'imageUrl': 'images/bage2.jpg',
    'title': 'Arrogant Monkey',
    'description': 'Arrogant Monkey cute monkey --- 15 pieces available',
    'code': '434',
    'id': 1,
    'price': 64.2,
  },
  {
    'imageUrl': 'images/bage4.png',
    'title': 'Crazy Monkey',
    'description': ' Crazy Monkey  ~~ Crazy Monkey -- 12 pieces available',
    'id': 2,
    'code': '763',
    'price': 12.0,
  },
  {
    'imageUrl': 'images/image1.jpg',
    'title': 'Crypto Punks',
    'description':
        'Crypto Punks most expensive paintings -- 1 pieces available',
    'code': '265',
    'id': 3,
    'price': 16.5,
  },
  {
    'imageUrl': 'images/image2.jpg',
    'title': 'Clone X',
    'description': 'Clone X Robot -- 50 pieces available',
    'code': '235',
    'id': 4,
    'price': 20.2,
  },
  {
    'imageUrl': 'images/image3.jpg',
    'title': 'Azuki',
    'description': 'Azuki from the anime -- 30 pieces available',
    'code': '756',
    'id': 5,
    'price': 16.0,
  },
  {
    'imageUrl': 'images/image4.jpg',
    'title': 'Crazy Monkey',
    'description': 'Crazy Monkey  from the stone age -- 12 pieces available',
    'code': '345',
    'price': 32.4,
    'id': 6,
  },
  {
    'imageUrl': 'images/image5.jpg',
    'title': 'Meebit',
    'description': 'Meebit wooden painting -- 20 pieces available',
    'code': '985',
    'id': 7,
    'price': 23.0,
  },
];
